;;; Declarative chunks

  (add-dm
   (p1 ISA comprehend-sentence relation in arg1 hippie arg2 park)
   (p2 ISA comprehend-sentence relation in arg1 hippie arg2 church)
   (p3 ISA comprehend-sentence relation in arg1 hippie arg2 bank)
   (p4 ISA comprehend-sentence relation in arg1 captain arg2 park)
   (p5 ISA comprehend-sentence relation in arg1 captain arg2 cave)
   (p6 ISA comprehend-sentence relation in arg1 debutante arg2 bank)
   (p7 ISA comprehend-sentence relation in arg1 fireman arg2 park)
   (p8 ISA comprehend-sentence relation in arg1 giant arg2 beach)
   (p9 ISA comprehend-sentence relation in arg1 giant arg2 castle)
   (p10 ISA comprehend-sentence relation in arg1 giant arg2 dungeon)
   (p11 ISA comprehend-sentence relation in arg1 earl arg2 castle)
   (p12 ISA comprehend-sentence relation in arg1 earl arg2 forest)
   (p13 ISA comprehend-sentence relation in arg1 lawyer arg2 store)
   (guard ISA meaning word "guard")
   (beach ISA meaning word "beach")
   (castle ISA meaning word "castle")
   (dungeon ISA meaning word "dungeon")
   (earl ISA meaning word "earl")
   (forest ISA meaning word "forest")
   (giant ISA meaning word "giant")
   (hippie ISA meaning word "hippie")
   (park ISA meaning word "park")
   (church ISA meaning word "church")
   (captain ISA meaning word "captain")
   (cave ISA meaning word "cave")
   (debutante ISA meaning word "debutante")
   (bank ISA meaning word "bank")
   (fireman ISA meaning word "fireman")
   (lawyer ISA meaning word "lawyer")
   (store ISA meaning word "store")
   (in ISA meaning word "in"))
  
  (set-base-levels
   (guard 10) (beach 10) (castle 10) (dungeon 10) (earl 10) 
   (forest 10) (hippie 10) (park 10) (church 10) (bank 10) 
   (captain 10) (cave 10) (giant 10) (debutante 10) (fireman 10)
   (lawyer 10) (store 10) (in 10))
  
;  (define-chunks (test isa chunk) (harvest-person isa chunk)
;    (harvest-location isa chunk) (get-retrieval isa chunk)
;    (goal isa sentence-goal state test))
  (define-chunks (goal isa sentence-goal state test))
  (goal-focus goal)
  
